// .res entries:
halflife.wad
sound/weapons/sbarrel1.wav
sound/ambience/siren.wav
sound/ambience/jetflyby1.wav
sound/ambience/star2.wav
sound/weapons/mortarhit.wav
sound/debris/beamstart11.wav
sound/weapons/electro5.wav
sprites/muzzleflash1.spr
sprites/steam1.spr
sprites/usaflagdoc.spr
/sprites/usat.spr
maps/crossfire.res
models/player/noelle/noelle.mdl
models/player/noelle/noelle.bmp
models/player/v1/v1.mdl
models/player/v1/v1.bmp
models/player/Mario64Odyssey/Mario64Odyssey.mdl
models/player/Mario64Odyssey/Mario64Odyssey.bmp
models/player/Steve_Clasico/Steve_Clasico.mdl
models/player/Steve_Clasico/Steve_Clasico.bmp
models/player/Alex_Clasica/Alex_Clasica.mdl
models/player/Alex_Clasica/Alex_Clasica.bmp
models/player/mercenary/mercenary.mdl
models/player/mercenary/mercenary.bmp
models/player/civilian_tf2c/civilian_tf2c.mdl
models/player/TFhvyweapon/TFhvyweapon.mdl
models/player/TFhvyweapon/TFhvyweapon.bmp
models/player/TFengineer/TFengineer.mdl
models/player/TFengineer/TFengineer.bmp
models/player/TFmedic/TFmedic.mdl
models/player/TFmedic/TFmedic.bmp
models/player/TFpyro/TFpyro.mdl
models/player/TFpyro/TFpyro.bmp
models/player/TFscout/TFscout.mdl
models/player/TFscout/TFscout.bmp
models/player/TFsniper/TFsniper.mdl
models/player/TFsniper/TFsniper.bmp
models/player/TFsoldier/TFsoldier.mdl
models/player/TFsoldier/TFsoldier.bmp
models/player/TFspy/TFspy.mdl
models/player/TFspy/TFspy.bmp
models/player/TFdemo/TFdemo.mdl
models/player/TFdemo/TFdemo.bmp
models/player/TFcivilian/TFcivilian.mdl
models/player/TFcivilian/TFcivilian.bmp
models/player/NecoArc/NecoArc.mdl
models/player/NecoArc/NecoArc.bmp
models/player/Sonic_Forces_Classic/Sonic_Forces_Classic.mdl
models/player/Sonic_Forces_Classic/Sonic_Forces_Classic.bmp
models/player/bradlio/bradlio.mdl
models/player/bradlio/bradlio.bmp
models/player/butthead/butthead.mdl
models/player/butthead/butthead.bmp
models/player/beavis/beavis.mdl
models/player/beavis/beavis.bmp
models/player/homero/homero.mdl
models/player/homero/homero.bmp
models/player/SpiderTASM2/SpiderTASM2.mdl
models/player/SpiderTASM2/SpiderTASM2.bmp
models/player/tp_colgate/tp_colgate.mdl
models/player/tp_colgate/tp_colgate.bmp
models/player/duke/duke.mdl
models/player/duke/duke.bmp
models/player/jesus/jesus.mdl
models/player/B2Caleb/B2Caleb.mdl
models/player/B2Caleb/B2Caleb.bmp
models/player/SpongeBob/SpongeBob.mdl
models/player/SpongeBob/SpongeBob.bmp
models/player/sonic_v4/sonic_v4.mdl
models/player/sonic_v4/sonic_v4.bmp
models/player/esf_vegeta1/esf_vegeta1.mdl
models/player/esf_vegeta1/esf_vegeta1.bmp
models/player/esf_goku/esf_goku.mdl
models/player/esf_goku/esf_goku.bmp
models/player/sa_cj/sa_cj.mdl
models/player/sa_cj/sa_cj.bmp
models/player/DrEggman/DrEggman.mdl
models/player/DrEggman/DrEggman.bmp
models/player/hanky/hanky.mdl
models/player/hanky/hanky.bmp
models/player/YoRHa_2B/YoRHa_2B.mdl
models/player/YoRHa_2B/YoRHa_2B.bmp
sound/player/playersounds/steve/dead.wav
sound/player/playersounds/tails/jump1.wav
sound/player/playersounds/tails/longjump2.wav
sound/player/playersounds/tails/lostring1.wav
models/player/pepsiman2/pepsiman2.mdl
models/player/pepsiman2/pepsiman2.bmp
models/player/PTEPOPUKO/PTEPOPUKO.mdl
models/player/PTEPOPUKO/PTEPOPUKO.bmp
models/player/PTEPIMIMI/PTEPIMIMI.mdl
models/player/PTEPIMIMI/PTEPIMIMI.bmp
sound/AQS/pancake.wav
sound/AQS/payback.wav
sound/AQS/pickupyourweaponsandfight.wav
sound/AQS/play.wav
sound/AQS/prepareforbattle.wav
sound/AQS/preparetofight.wav
sound/AQS/rampage.wav
sound/AQS/rampage2.wav
sound/AQS/retribution.wav
sound/AQS/teamkiller.wav
sound/AQS/triplekill.wav
sound/AQS/ultrakill.wav
sound/AQS/ultrakill2.wav
sound/AQS/unreal.wav
sound/AQS/unstoppable.wav
sound/AQS/unstoppable2.wav
sound/AQS/vengeance.wav
sound/AQS/whickedsick.wav
sound/AQS/youarethelastmanstanding.wav
sound/AQS/yourefunny.wav
sound/AQS/assassin.wav
sound/AQS/bullseye.wav
sound/AQS/comboking.wav
sound/AQS/dominating.wav
sound/AQS/dominating2.wav
sound/AQS/doublekill.wav
sound/AQS/doublekill2.wav
sound/AQS/doublekill3.wav
sound/AQS/eagleeye.wav
sound/AQS/eagleeye2.wav
sound/AQS/excellent.wav
sound/AQS/firstblood.wav
sound/AQS/firstblood2.wav
sound/AQS/firstblood3.wav
sound/AQS/firstblood4.wav
sound/AQS/flawlessvictory.wav
sound/AQS/godlike.wav
sound/AQS/godlike2.wav
sound/AQS/hattrick.wav
sound/AQS/hattrick2.wav
sound/AQS/headhunter.wav
sound/AQS/headhunter2.wav
sound/AQS/headshot.wav
sound/AQS/headshot2.wav
sound/AQS/headshot3.wav
sound/AQS/headshot4.wav
sound/AQS/holyshit.wav
sound/AQS/humiliating.wav
sound/AQS/humiliatingdefeat.wav
sound/AQS/humiliation.wav
sound/AQS/iamtheoneandonly.wav
sound/AQS/impressive.wav
sound/AQS/killingmachine.wav
sound/AQS/killingspree.wav
sound/AQS/killingspree2.wav
sound/AQS/laughs.wav
sound/AQS/laughs2.wav
sound/AQS/laughs3.wav
sound/AQS/laughs4.wav
sound/AQS/ludicrouskill.wav
sound/AQS/maniac.wav
sound/AQS/massacre.wav
sound/AQS/megakill.wav
sound/AQS/megakill2.wav
sound/AQS/monsterkill.wav
sound/AQS/monsterkill2.wav
sound/AQS/multikill.wav
sound/AQS/multikill2.wav
sound/AQS/outstanding.wav
sound/AQS/ownage.wav
sound/AQS/vox/monsterkill.wav
sound/AQS/vox/multikill.wav
sound/AQS/vox/oustanding.wav
sound/AQS/vox/ownage.wav
sound/AQS/vox/pancake.wav
sound/AQS/vox/payback.wav
sound/AQS/vox/pickupyourweaponsandfight.wav
sound/AQS/vox/play.wav
sound/AQS/vox/prepareforbattle.wav
sound/AQS/vox/preparetofight.wav
sound/AQS/vox/rampage.wav
sound/AQS/vox/retribution.wav
sound/AQS/vox/teamkiller.wav
sound/AQS/vox/triplekill.wav
sound/AQS/vox/ultrakill.wav
sound/AQS/vox/unreal.wav
sound/AQS/vox/unstoppable.wav
sound/AQS/vox/vengeance.wav
sound/AQS/vox/whickedsick.wav
sound/AQS/vox/youarethelastmanstanding.wav
sound/AQS/vox/assassin.wav
sound/AQS/vox/bullseye.wav
sound/AQS/vox/comboking.wav
sound/AQS/vox/dominating.wav
sound/AQS/vox/doublekill.wav
sound/AQS/vox/doublekill2.wav
sound/AQS/vox/doublekill3.wav
sound/AQS/vox/eagleeye.wav
sound/AQS/vox/excellent.wav
sound/AQS/vox/firstblood.wav
sound/AQS/vox/firstblood2.wav
sound/AQS/vox/firstblood3.wav
sound/AQS/vox/firstblood4.wav
sound/AQS/vox/flawlessvictory.wav
sound/AQS/vox/godlike.wav
sound/AQS/vox/hattrick.wav
sound/AQS/vox/hattrick2.wav
sound/AQS/vox/headhunter.wav
sound/AQS/vox/headshot.wav
sound/AQS/vox/headshot2.wav
sound/AQS/vox/headshot3.wav
sound/AQS/vox/headshot4.wav
sound/AQS/vox/holyshit.wav
sound/AQS/vox/humiliation.wav
sound/AQS/vox/iamtheoneandonly.wav
sound/AQS/vox/impressive.wav
sound/AQS/vox/killingmachine.wav
sound/AQS/vox/killingspree.wav
sound/AQS/vox/laughs2.wav
sound/AQS/vox/ludicrouskill.wav
sound/AQS/vox/maniac.wav
sound/AQS/vox/massacre.wav
sound/AQS/vox/megakill.wav