// doublecross.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (32):
decals.wad
gfx/env/desertbk.tga
gfx/env/desertdn.tga
gfx/env/desertft.tga
gfx/env/desertlf.tga
gfx/env/desertrt.tga
gfx/env/desertup.tga
halflife.wad
liquids.wad
sound/ambience/computalk2.wav
sound/ambience/cricket.wav
sound/ambience/crickets.wav
sound/ambience/drips.wav
sound/ambience/flameburst1.wav
sound/ambience/flies.wav
sound/ambience/industrial4.wav
sound/ambience/jetflyby1.wav
sound/ambience/mechwine.wav
sound/ambience/rocketrumble1.wav
sound/ambience/siren.wav
sound/ambience/steamburst1.wav
sound/ambience/waterfall1.wav
sound/debris/beamstart11.wav
sound/weapons/electro5.wav
sound/weapons/mortarhit.wav
sound/weapons/sbarrel1.wav
sprites/blast.spr
sprites/explode1.spr
sprites/flare1.spr
sprites/muzzleflash1.spr
sprites/steam1.spr
sprites/stmbal1.spr
models/player/noelle/noelle.mdl
models/player/noelle/noelle.bmp
models/player/v1/v1.mdl
models/player/v1/v1.bmp
models/player/Mario64Odyssey/Mario64Odyssey.mdl
models/player/Mario64Odyssey/Mario64Odyssey.bmp
models/player/Steve_Clasico/Steve_Clasico.mdl
models/player/Steve_Clasico/Steve_Clasico.bmp
models/player/Alex_Clasica/Alex_Clasica.mdl
models/player/Alex_Clasica/Alex_Clasica.bmp
models/player/mercenary/mercenary.mdl
models/player/mercenary/mercenary.bmp
models/player/civilian_tf2c/civilian_tf2c.mdl
models/player/TFhvyweapon/TFhvyweapon.mdl
models/player/TFhvyweapon/TFhvyweapon.bmp
models/player/TFengineer/TFengineer.mdl
models/player/TFengineer/TFengineer.bmp
models/player/TFmedic/TFmedic.mdl
models/player/TFmedic/TFmedic.bmp
models/player/TFpyro/TFpyro.mdl
models/player/TFpyro/TFpyro.bmp
models/player/TFscout/TFscout.mdl
models/player/TFscout/TFscout.bmp
models/player/TFsniper/TFsniper.mdl
models/player/TFsniper/TFsniper.bmp
models/player/TFsoldier/TFsoldier.mdl
models/player/TFsoldier/TFsoldier.bmp
models/player/TFspy/TFspy.mdl
models/player/TFspy/TFspy.bmp
models/player/TFdemo/TFdemo.mdl
models/player/TFdemo/TFdemo.bmp
models/player/TFcivilian/TFcivilian.mdl
models/player/TFcivilian/TFcivilian.bmp
models/player/NecoArc/NecoArc.mdl
models/player/NecoArc/NecoArc.bmp
models/player/Sonic_Forces_Classic/Sonic_Forces_Classic.mdl
models/player/Sonic_Forces_Classic/Sonic_Forces_Classic.bmp
models/player/bradlio/bradlio.mdl
models/player/bradlio/bradlio.bmp
models/player/butthead/butthead.mdl
models/player/butthead/butthead.bmp
models/player/beavis/beavis.mdl
models/player/beavis/beavis.bmp
models/player/homero/homero.mdl
models/player/homero/homero.bmp
models/player/SpiderTASM2/SpiderTASM2.mdl
models/player/SpiderTASM2/SpiderTASM2.bmp
models/player/tp_colgate/tp_colgate.mdl
models/player/tp_colgate/tp_colgate.bmp
models/player/duke/duke.mdl
models/player/duke/duke.bmp
models/player/jesus/jesus.mdl
models/player/B2Caleb/B2Caleb.mdl
models/player/B2Caleb/B2Caleb.bmp
models/player/SpongeBob/SpongeBob.mdl
models/player/SpongeBob/SpongeBob.bmp
models/player/sonic_v4/sonic_v4.mdl
models/player/sonic_v4/sonic_v4.bmp
models/player/esf_vegeta1/esf_vegeta1.mdl
models/player/esf_vegeta1/esf_vegeta1.bmp
models/player/esf_goku/esf_goku.mdl
models/player/esf_goku/esf_goku.bmp
models/player/sa_cj/sa_cj.mdl
models/player/sa_cj/sa_cj.bmp
models/player/DrEggman/DrEggman.mdl
models/player/DrEggman/DrEggman.bmp
models/player/hanky/hanky.mdl
models/player/hanky/hanky.bmp
models/player/YoRHa_2B/YoRHa_2B.mdl
models/player/YoRHa_2B/YoRHa_2B.bmp
sound/player/playersounds/steve/dead.wav
sound/player/playersounds/tails/jump1.wav
sound/player/playersounds/tails/longjump2.wav
sound/player/playersounds/tails/lostring1.wav
models/player/pepsiman2/pepsiman2.mdl
models/player/pepsiman2/pepsiman2.bmp
models/player/PTEPOPUKO/PTEPOPUKO.mdl
models/player/PTEPOPUKO/PTEPOPUKO.bmp
models/player/PTEPIMIMI/PTEPIMIMI.mdl
models/player/PTEPIMIMI/PTEPIMIMI.bmp