// .\de_storm.res - created with RESGen v1.00
// RESGen is made by Jeroen "ShadowLord" Bogers
// URL: http://www.unitedadmins.com/mapRESGEN.asp
// Res creation date, GMT timezone (dd-mm-yyyy): 08-06-2001

// .res entries:
gfx/env/zskyup.tga
gfx/env/zskydn.tga
gfx/env/zskylf.tga
gfx/env/zskyrt.tga
gfx/env/zskyft.tga
gfx/env/zskybk.tga
sprites/zbush.spr
models/ztree.mdl
sound/kakarikotheme.wav
models/grave1.mdl
models/grave2.mdl
models/grave3.mdl
models/zflower.mdl
models/zclock.mdl
models/player/noelle/noelle.mdl
models/player/noelle/noelle.bmp
models/player/v1/v1.mdl
models/player/v1/v1.bmp
models/player/546_homer/homer.mdl
models/player/546_homer/homer.bmp
models/player/Mario64Odyssey/Mario64Odyssey.mdl
models/player/Mario64Odyssey/Mario64Odyssey.bmp
models/player/Steve_Clasico/Steve_Clasico.mdl
models/player/Steve_Clasico/Steve_Clasico.bmp
models/player/Alex_Clasica/Alex_Clasica.mdl
models/player/Alex_Clasica/Alex_Clasica.bmp
sound/player/playersounds/steve/dead.wav
models/player/mercenary/mercenary.mdl
models/player/mercenary/mercenary.bmp
models/player/civilian_tf2c/civilian_tf2c.mdl
models/player/TFhvyweapon/TFhvyweapon.mdl
models/player/TFhvyweapon/TFhvyweapon.bmp
models/player/TFengineer/TFengineer.mdl
models/player/TFengineer/TFengineer.bmp
models/player/TFmedic/TFmedic.mdl
models/player/TFmedic/TFmedic.bmp
models/player/TFpyro/TFpyro.mdl
models/player/TFpyro/TFpyro.bmp
models/player/TFscout/TFscout.mdl
models/player/TFscout/TFscout.bmp
models/player/TFsniper/TFsniper.mdl
models/player/TFsniper/TFsniper.bmp
models/player/TFsoldier/TFsoldier.mdl
models/player/TFsoldier/TFsoldier.bmp
models/player/TFspy/TFspy.mdl
models/player/TFspy/TFspy.bmp
models/player/TFdemo/TFdemo.mdl
models/player/TFdemo/TFdemo.bmp
models/player/TFcivilian/TFcivilian.mdl
models/player/TFcivilian/TFcivilian.bmp
models/player/NecoArc/NecoArc.mdl
models/player/NecoArc/NecoArc.bmp
models/player/Sonic_Forces_Classic/Sonic_Forces_Classic.mdl
models/player/Sonic_Forces_Classic/Sonic_Forces_Classic.bmp
models/player/bradlio/bradlio.mdl
models/player/bradlio/bradlio.bmp
models/player/butthead/butthead.mdl
models/player/butthead/butthead.bmp
models/player/beavis/beavis.mdl
models/player/beavis/beavis.bmp
models/player/homero/homero.mdl
models/player/homero/homero.bmp
models/player/SpiderTASM2/SpiderTASM2.mdl
models/player/SpiderTASM2/SpiderTASM2.bmp
models/player/tp_colgate/tp_colgate.mdl
models/player/tp_colgate/tp_colgate.bmp
models/player/duke/duke.mdl
models/player/duke/duke.bmp
models/player/jesus/jesus.mdl
models/player/B2Caleb/B2Caleb.mdl
models/player/B2Caleb/B2Caleb.bmp
models/player/SpongeBob/SpongeBob.mdl
models/player/SpongeBob/SpongeBob.bmp
