// nook_rats.res
// ----------------------------
// Thu Apr 15 10:18:16 2021

// NOTE: Items commented out do not need to be enabled for download - they are downloaded by the server automatically

// map related files - the bsp does not need to be listed but the readme (if available) and the res file do need to be listed
//maps/nook_rats.bsp
maps/nook_rats.res
maps/nook_rats.txt 
gfx/env/skylinebk.tga
gfx/env/skylinedn.tga
gfx/env/skylineft.tga
gfx/env/skylinelf.tga
gfx/env/skylinert.tga
gfx/env/skylineup.tga
models/nook/bigfatrat.mdl
overviews/nook_rats.tga
overviews/nook_rats.txt
//sound/nook/atm01.wav
//sound/nook/atm02.wav
//sound/nook/nook_speak.wav
//sound/nook/residential.wav
//sprites/nook/tom_nook.spr
models/player/noelle/noelle.mdl
models/player/noelle/noelle.bmp
models/player/v1/v1.mdl
models/player/v1/v1.bmp
models/player/Mario64Odyssey/Mario64Odyssey.mdl
models/player/Mario64Odyssey/Mario64Odyssey.bmp
models/player/Steve_Clasico/Steve_Clasico.mdl
models/player/Steve_Clasico/Steve_Clasico.bmp
models/player/Alex_Clasica/Alex_Clasica.mdl
models/player/Alex_Clasica/Alex_Clasica.bmp
models/player/mercenary/mercenary.mdl
models/player/mercenary/mercenary.bmp
models/player/civilian_tf2c/civilian_tf2c.mdl
models/player/TFhvyweapon/TFhvyweapon.mdl
models/player/TFhvyweapon/TFhvyweapon.bmp
models/player/TFengineer/TFengineer.mdl
models/player/TFengineer/TFengineer.bmp
models/player/TFmedic/TFmedic.mdl
models/player/TFmedic/TFmedic.bmp
models/player/TFpyro/TFpyro.mdl
models/player/TFpyro/TFpyro.bmp
models/player/TFscout/TFscout.mdl
models/player/TFscout/TFscout.bmp
models/player/TFsniper/TFsniper.mdl
models/player/TFsniper/TFsniper.bmp
models/player/TFsoldier/TFsoldier.mdl
models/player/TFsoldier/TFsoldier.bmp
models/player/TFspy/TFspy.mdl
models/player/TFspy/TFspy.bmp
models/player/TFdemo/TFdemo.mdl
models/player/TFdemo/TFdemo.bmp
models/player/TFcivilian/TFcivilian.mdl
models/player/TFcivilian/TFcivilian.bmp
models/player/NecoArc/NecoArc.mdl
models/player/NecoArc/NecoArc.bmp
models/player/Sonic_Forces_Classic/Sonic_Forces_Classic.mdl
models/player/Sonic_Forces_Classic/Sonic_Forces_Classic.bmp
models/player/bradlio/bradlio.mdl
models/player/bradlio/bradlio.bmp
models/player/butthead/butthead.mdl
models/player/butthead/butthead.bmp
models/player/beavis/beavis.mdl
models/player/beavis/beavis.bmp
models/player/homero/homero.mdl
models/player/homero/homero.bmp
models/player/SpiderTASM2/SpiderTASM2.mdl
models/player/SpiderTASM2/SpiderTASM2.bmp
models/player/tp_colgate/tp_colgate.mdl
models/player/tp_colgate/tp_colgate.bmp
models/player/duke/duke.mdl
models/player/duke/duke.bmp
models/player/jesus/jesus.mdl
models/player/B2Caleb/B2Caleb.mdl
models/player/B2Caleb/B2Caleb.bmp
models/player/SpongeBob/SpongeBob.mdl
models/player/SpongeBob/SpongeBob.bmp
models/player/sonic_v4/sonic_v4.mdl
models/player/sonic_v4/sonic_v4.bmp
models/player/esf_vegeta1/esf_vegeta1.mdl
models/player/esf_vegeta1/esf_vegeta1.bmp
models/player/esf_goku/esf_goku.mdl
models/player/esf_goku/esf_goku.bmp
models/player/sa_cj/sa_cj.mdl
models/player/sa_cj/sa_cj.bmp
models/player/DrEggman/DrEggman.mdl
models/player/DrEggman/DrEggman.bmp
models/player/hanky/hanky.mdl
models/player/hanky/hanky.bmp
models/player/YoRHa_2B/YoRHa_2B.mdl
models/player/YoRHa_2B/YoRHa_2B.bmp
sound/player/playersounds/steve/dead.wav
sound/player/playersounds/tails/jump1.wav
sound/player/playersounds/tails/longjump2.wav
sound/player/playersounds/tails/lostring1.wav
models/player/pepsiman2/pepsiman2.mdl
models/player/pepsiman2/pepsiman2.bmp
models/player/PTEPOPUKO/PTEPOPUKO.mdl
models/player/PTEPOPUKO/PTEPOPUKO.bmp
models/player/PTEPIMIMI/PTEPIMIMI.mdl
models/player/PTEPIMIMI/PTEPIMIMI.bmp
models/player/pumpkin/pumpkin.mdl
models/player/pumpkin/pumpkin.bmp
models/player/santa/santa.mdl
models/player/santa/santa.bmp
models/player/homestar/homestar.mdl
models/player/homestar/homestar.bmp
models/player/sp_phillip/sp_phillip.mdl
models/player/sp_phillip/sp_phillip.bmp
models/player/sp_terrance/sp_terrance.mdl
models/player/sp_terrance/sp_terrance.bmp